defaults:
  - _self_
  - data: litho-pair
  - model: rfno
  - callbacks: gen
  - logger: aim
  - trainer: litho
  - paths: default
  - extras: default
  - hydra: default

  - experiment: null

  - hparams_search: null

  - optional local: default

  - debug: null

task_name: "doinn-fused"

tags: ["doinn"]

doinn: True

test: True

ckpt_path: null

seed: null
