defaults:
  - _self_
  - data: litho-pair
  - model: socs
  - callbacks: gen
  - logger: aim
  - trainer: litho
  - paths: default
  - extras: default
  - hydra: default

  - experiment: null

  - hparams_search: null

  - optional local: default

  - debug: null

task_name: "socs-fused"

tags: ["socs"]

socs: True

test: True

ckpt_path: null

seed: null
